### ISSUE TITLE
Exception while casting the long to int

### ISSUE THREAD

**Issue by anisnasir** [gdfm/partial-key-grouping#1]
int firstChoice = (int) Math.abs(h1.hashBytes(str.getBytes()).asLong()) % this.targetTasks.size();
int secondChoice = (int) Math.abs(h2.hashBytes(str.getBytes()).asLong()) % this.targetTasks.size();

required to be updated to:

int firstChoice = (int) (Math.abs(h1.hashBytes(str.getBytes()).asLong()) % this.targetTasks.size() );
int secondChoice = (int) (Math.abs(h2.hashBytes(str.getBytes()).asLong()) % this.targetTasks.size());

**Comment by gdfm** [comment]
why is that? doesn't the cast take care of the long? and the size() should return an int.

**Comment by anisnasir** [comment]
The expression will first convert the long to int and then apply the mod. Therefore, for some hashes it might return unexpected values.

**Comment by gdfm** [comment]
I see, the cast has higher priority than the modulo.
OK, fixed in #2.
Thanks!
